name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Build and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sh build.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/tvbox.zip
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: tvbox-${{ github.event.inputs.version }}
          name: tvbox-${{ github.event.inputs.version }}

